name 'core-setup'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures core-setup'
long_description 'Installs/Configures core-setup'
version '0.1.0'

depends 'apt'
depends 'build-essential'
depends 'chrony'
depends 'git'
